/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class frameProvinsi extends javax.swing.JFrame {

    koneksi myObject;
    
    public DefaultTableModel modelTabelProvinsi;
    
    /**
     * Creates new form frameProvinsi
     */
    public frameProvinsi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        myObject = new koneksi();
        modelTabelProvinsi = new DefaultTableModel();
        tabelProvinsi.setModel(modelTabelProvinsi);
        modelTabelProvinsi.addColumn("ID Komoditas");
        modelTabelProvinsi.addColumn("Nama Komoditas");
        tampilDataProvinsi();
    }

    public void tampilDataProvinsi() {
        try {
            modelTabelProvinsi.getDataVector().removeAllElements();
            modelTabelProvinsi.fireTableDataChanged();
            
            PreparedStatement query = myObject.konek.prepareStatement("SELECT * FROM provinsi");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[2];
                baris[0] = data.getString("id_provinsi");
                baris[1] = data.getString("nama_provinsi");
                modelTabelProvinsi.addRow(baris);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamaProvinsi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDProvinsi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProvinsi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("ID Provinsi");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tambah Data Provinsi");

        jLabel2.setText("Nama Provinsi");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan PreparedStatement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelProvinsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelProvinsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProvinsiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProvinsi);

        jLabel10.setText("Cari Data");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamaProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIDProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(txtCari))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIDProvinsi, txtNamaProvinsi});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID komoditas belum di isi!");
                txtIDProvinsi.requestFocus();
            } else if (txtNamaProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama provinsi belum di isi!");
                txtNamaProvinsi.requestFocus();
                 } else {
                String sql = "insert into provinsi value ('"+txtIDProvinsi.getText()+"','"+txtNamaProvinsi.getText()+"')";
                myObject.konek.createStatement().execute(sql);
                tampilDataProvinsi();
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelProvinsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProvinsiMouseClicked
        // TODO add your handling code here:
        int baris = tabelProvinsi.getSelectedRow();
        String id_provinsi = tabelProvinsi.getValueAt(baris, 0).toString();
        String nama_provinsi = tabelProvinsi.getValueAt(baris, 1).toString();
        txtIDProvinsi.setText(id_provinsi);
        txtNamaProvinsi.setText(nama_provinsi);
    }//GEN-LAST:event_tabelProvinsiMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Provinsi belum di isi!");
                txtIDProvinsi.requestFocus();
            } else if (txtNamaProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama Provinsi belum di isi!");
                txtNamaProvinsi.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM provinsi WHERE id_provinsi ='"+txtIDProvinsi.getText()+"'";
                ResultSet cari = myObject.konek.createStatement().executeQuery(sqlCari);
                if(cari.next()){
                    JOptionPane.showMessageDialog(this, "ID Provinsi sudah terdaftar!!!");
                                         
                    txtNamaProvinsi.setText(cari.getString(2));
                    
                } else {
                    String sql = "INSERT INTO provinsi VALUE (?, ?)";
                    PreparedStatement simpan = myObject.konek.prepareStatement(sql);
                    simpan.setString(1, txtIDProvinsi.getText());
                    simpan.setString(2, txtNamaProvinsi.getText());
                    simpan.executeUpdate();
                    tampilDataProvinsi();
                    JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDProvinsi.getText().isEmpty()) &&
                    (txtNamaProvinsi.getText().isEmpty()) 
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE provinsi SET nama_provinsi=? WHERE id_provinsi=?";
                PreparedStatement ubah = myObject.konek.prepareStatement(sql);
                ubah.setString(1, txtNamaProvinsi.getText());
                ubah.setString(2, txtIDProvinsi.getText());
                ubah.executeUpdate();
                tampilDataProvinsi();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDProvinsi.getText().isEmpty()) &&
                    (txtNamaProvinsi.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM provinsi WHERE id_provinsi=?";
                PreparedStatement hapus = myObject.konek.prepareStatement(sql);
                hapus.setString(1, txtIDProvinsi.getText());
                hapus.executeUpdate();
                tampilDataProvinsi();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        modelTabelProvinsi.getDataVector().removeAllElements();
        modelTabelProvinsi.fireTableDataChanged();
        try {
            String sqlcari = "SELECT * FROM provinsi WHERE id_provinsi LIKE '%"+txtCari.getText()+"%' "
                        + "OR nama_provinsi LIKE '%"+txtCari.getText()+"%'";
            Statement cari = myObject.konek.createStatement();
            ResultSet data = cari.executeQuery(sqlcari);
            while (data.next()) {                
                Object[] baris = new Object[2];
                baris[0] = data.getString("id_provinsi");
                baris[1] = data.getString("nama_provinsi");
                modelTabelProvinsi.addRow(baris);   
            }
            cari.close();
            data.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameProvinsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameProvinsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameProvinsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameProvinsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameProvinsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProvinsi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIDProvinsi;
    private javax.swing.JTextField txtNamaProvinsi;
    // End of variables declaration//GEN-END:variables
}
