/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class frameBukaLelang extends javax.swing.JFrame {

    koneksi myObject;
    
    public DefaultTableModel modelTabelBukaLelang;
    
    /**
     * Creates new form frameBukaLelang
     */
    public frameBukaLelang() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        myObject = new koneksi();
        modelTabelBukaLelang = new DefaultTableModel();
        tabelBukaLelang.setModel(modelTabelBukaLelang);
        modelTabelBukaLelang.addColumn("ID Buka Lelang");
        modelTabelBukaLelang.addColumn("ID Petani");
        modelTabelBukaLelang.addColumn("ID Komoditas");
        modelTabelBukaLelang.addColumn("Berat Total");
        modelTabelBukaLelang.addColumn("Harga Awal");
        modelTabelBukaLelang.addColumn("Tanggal Buka");
        modelTabelBukaLelang.addColumn("Tanggal Habis");
        modelTabelBukaLelang.addColumn("Waktu Habis");
        tampilDataBukaLelang();
    }
    
    public void tampilDataBukaLelang() {
        try {
            modelTabelBukaLelang.getDataVector().removeAllElements();
            modelTabelBukaLelang.fireTableDataChanged();
            
            PreparedStatement query = myObject.konek.prepareStatement("SELECT * FROM buka_lelang");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[8];
                baris[0] = data.getString("id_bukalelang");
                baris[1] = data.getString("id_petani");
                baris[2] = data.getString("id_komoditas");
                baris[3] = data.getString("berat_total");
                baris[4] = data.getString("harga_awal");
                baris[5] = data.getString("tanggal_buka");
                baris[6] = data.getString("tanggal_habis");
                baris[7] = data.getString("waktu_habis");
                modelTabelBukaLelang.addRow(baris);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDBukaLelang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIDPetani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDKomoditas = new javax.swing.JTextField();
        txtBeratTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHargaAwal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTanggalBuka = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTanggalHabis = new javax.swing.JTextField();
        txtWaktuHabis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBukaLelang = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tambah Data Buka Lelang");

        jLabel2.setText("ID Buka Lelang");

        jLabel3.setText("ID Petani");

        jLabel4.setText("ID Komoditas");

        jLabel5.setText("Berat Total");

        jLabel6.setText("Harga Awal");

        jLabel7.setText("Tanggal Buka");

        jLabel8.setText("Tanggal Habis");

        jLabel9.setText("Waktu Habis");

        jButton1.setText("Simpan PreparedStatement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabelBukaLelang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBukaLelang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBukaLelangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBukaLelang);

        jButton4.setText("Simpan Statement");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel10.setText("Cari Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIDBukaLelang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBeratTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIDKomoditas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTanggalBuka, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtWaktuHabis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTanggalHabis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDPetani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addGap(60, 60, 60)
                                    .addComponent(jButton1))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBeratTotal, txtHargaAwal, txtIDBukaLelang, txtIDKomoditas, txtIDPetani, txtTanggalBuka, txtTanggalHabis, txtWaktuHabis});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDBukaLelang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIDPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDKomoditas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBeratTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTanggalBuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTanggalHabis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtWaktuHabis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDBukaLelang.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Buka lelang belum di isi!");
                txtIDBukaLelang.requestFocus();
            } else if (txtIDPetani.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Petani belum di isi!");
                txtIDPetani.requestFocus();
            } else if (txtIDKomoditas.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Komoditas belum di isi!");
                txtIDKomoditas.requestFocus();
            } else if (txtBeratTotal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Berat total belum di isi!");
                txtBeratTotal.requestFocus();
            } else if (txtHargaAwal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Harga awal belum di isi!");
                txtHargaAwal.requestFocus();
            } else if (txtTanggalBuka.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal buka belum di isi!");
                txtTanggalBuka.requestFocus();
            } else if (txtTanggalHabis.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal habis belum di isi!");
                txtTanggalHabis.requestFocus();
            } else if (txtWaktuHabis.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Waktu habis belum di isi!");
                txtWaktuHabis.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM buka_lelang WHERE id_bukalelang ='"+txtIDBukaLelang.getText()+"'";
                ResultSet cari = myObject.konek.createStatement().executeQuery(sqlCari);
                if(cari.next()){
                    JOptionPane.showMessageDialog(this, "ID Buka lelang sudah terdaftar!!!");
                                         
                    txtIDPetani.setText(cari.getString(2));
                    txtIDKomoditas.setText(cari.getString(3));
                    txtBeratTotal.setText(cari.getString(4));
                    txtHargaAwal.setText(cari.getString(5));
                    txtTanggalBuka.setText(cari.getString(6));
                    txtTanggalHabis.setText(cari.getString(7));
                    txtWaktuHabis.setText(cari.getString(8));
                    
                } else {
                    String sql = "INSERT INTO buka_lelang VALUE (?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement simpan = myObject.konek.prepareStatement(sql);
                    simpan.setString(1, txtIDBukaLelang.getText());
                    simpan.setString(2, txtIDPetani.getText());
                    simpan.setString(3, txtIDKomoditas.getText());
                    simpan.setString(4, txtBeratTotal.getText());
                    simpan.setString(5, txtHargaAwal.getText());
                    simpan.setString(6, txtTanggalBuka.getText());
                    simpan.setString(7, txtTanggalHabis.getText());
                    simpan.setString(8, txtWaktuHabis.getText());
                    simpan.executeUpdate();
                    tampilDataBukaLelang();
                    JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelBukaLelangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBukaLelangMouseClicked
        // TODO add your handling code here:
        int baris = tabelBukaLelang.getSelectedRow();
        String id_bukalelang = tabelBukaLelang.getValueAt(baris, 0).toString();
        String id_petani = tabelBukaLelang.getValueAt(baris, 1).toString();
        String id_komoditas = tabelBukaLelang.getValueAt(baris, 2).toString();
        String berat_total = tabelBukaLelang.getValueAt(baris, 3).toString();
        String harga_awal = tabelBukaLelang.getValueAt(baris, 4).toString();
        String tanggal_buka = tabelBukaLelang.getValueAt(baris, 5).toString();
        String tanggal_habis = tabelBukaLelang.getValueAt(baris, 6).toString();
        String waktu_habis = tabelBukaLelang.getValueAt(baris, 7).toString();
        txtIDBukaLelang.setText(id_bukalelang);
        txtIDPetani.setText(id_petani);
        txtIDKomoditas.setText(id_komoditas);
        txtBeratTotal.setText(berat_total);
        txtHargaAwal.setText(harga_awal);
        txtTanggalBuka.setText(tanggal_buka);
        txtTanggalHabis.setText(tanggal_habis);
        txtWaktuHabis.setText(waktu_habis);
    }//GEN-LAST:event_tabelBukaLelangMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDBukaLelang.getText().isEmpty()) &&
                    (txtIDPetani.getText().isEmpty()) &&
                    (txtIDKomoditas.getText().isEmpty()) &&
                    (txtBeratTotal.getText().isEmpty()) &&
                    (txtHargaAwal.getText().isEmpty()) &&
                    (txtTanggalBuka.getText().isEmpty()) &&
                    (txtTanggalHabis.getText().isEmpty()) &&
                    (txtWaktuHabis.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM buka_lelang WHERE id_bukalelang=?";
                PreparedStatement hapus = myObject.konek.prepareStatement(sql);
                hapus.setString(1, txtIDBukaLelang.getText());
                hapus.executeUpdate();
                tampilDataBukaLelang();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDBukaLelang.getText().isEmpty()) &&
                    (txtIDPetani.getText().isEmpty()) &&
                    (txtIDKomoditas.getText().isEmpty()) &&
                    (txtBeratTotal.getText().isEmpty()) &&
                    (txtHargaAwal.getText().isEmpty()) &&
                    (txtTanggalBuka.getText().isEmpty()) &&
                    (txtTanggalHabis.getText().isEmpty()) &&
                    (txtWaktuHabis.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE buka_lelang SET id_petani=?, id_komoditas=?, berat_total=?, harga_awal=?, tanggal_buka=?, tanggal_habis=?, waktu_habis=? WHERE id_bukalelang=?";
                PreparedStatement ubah = myObject.konek.prepareStatement(sql);
                ubah.setString(1, txtIDPetani.getText());
                ubah.setString(2, txtIDKomoditas.getText());
                ubah.setString(3, txtBeratTotal.getText());
                ubah.setString(4, txtHargaAwal.getText());
                ubah.setString(5, txtTanggalBuka.getText());
                ubah.setString(6, txtTanggalHabis.getText());
                ubah.setString(7, txtWaktuHabis.getText());
                ubah.setString(8, txtIDBukaLelang.getText());
                ubah.executeUpdate();
                tampilDataBukaLelang();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDBukaLelang.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Buka lelang belum di isi!");
                txtIDBukaLelang.requestFocus();
            } else if (txtIDPetani.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Petani belum di isi!");
                txtIDPetani.requestFocus();
            } else if (txtIDKomoditas.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Komoditas belum di isi!");
                txtIDKomoditas.requestFocus();
            } else if (txtBeratTotal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Berat total belum di isi!");
                txtBeratTotal.requestFocus();
            } else if (txtHargaAwal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Harga awal belum di isi!");
                txtHargaAwal.requestFocus();
            } else if (txtTanggalBuka.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal buka belum di isi!");
                txtTanggalBuka.requestFocus();
            } else if (txtTanggalHabis.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal habis belum di isi!");
                txtTanggalHabis.requestFocus();
            } else if (txtWaktuHabis.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Waktu habis belum di isi!");
                txtWaktuHabis.requestFocus();
            } else {
                String sql = "insert into buka_lelang value ('"+txtIDBukaLelang.getText()+"','"+txtIDPetani.getText()+"','"+txtIDKomoditas.getText()+"','"+txtBeratTotal.getText()+"','"+txtHargaAwal.getText()+"','"+txtTanggalBuka.getText()+"','"+txtTanggalHabis.getText()+"','"+txtWaktuHabis.getText()+"')";
                myObject.konek.createStatement().execute(sql);
                tampilDataBukaLelang();
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        modelTabelBukaLelang.getDataVector().removeAllElements();
        modelTabelBukaLelang.fireTableDataChanged();
        try {
            String sqlcari = "SELECT * FROM buka_lelang WHERE id_bukalelang LIKE '%"+txtCari.getText()+"%' "
                        + "OR id_petani LIKE '%"+txtCari.getText()+"%' OR id_komoditas LIKE '%"+txtCari.getText()+"%'"
                        + "OR berat_total LIKE '%"+txtCari.getText()+"%' OR harga_awal LIKE '%"+txtCari.getText()+"%'"
                        + "OR tanggal_buka LIKE '%"+txtCari.getText()+"%' OR tanggal_habis LIKE '%"+txtCari.getText()+"%'"
                        + "OR waktu_habis LIKE '%"+txtCari.getText()+"%'";
            Statement cari = myObject.konek.createStatement();
            ResultSet data = cari.executeQuery(sqlcari);
            while (data.next()) {                
                Object[] baris = new Object[8];
                baris[0] = data.getString("id_bukalelang");
                baris[1] = data.getString("id_petani");
                baris[2] = data.getString("id_komoditas");
                baris[3] = data.getString("berat_total");
                baris[4] = data.getString("harga_awal");
                baris[5] = data.getString("tanggal_buka");
                baris[6] = data.getString("tanggal_habis");
                baris[7] = data.getString("waktu_habis");
                modelTabelBukaLelang.addRow(baris);   
            }
            cari.close();
            data.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBukaLelang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBukaLelang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBukaLelang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBukaLelang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBukaLelang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBukaLelang;
    private javax.swing.JTextField txtBeratTotal;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaAwal;
    private javax.swing.JTextField txtIDBukaLelang;
    private javax.swing.JTextField txtIDKomoditas;
    private javax.swing.JTextField txtIDPetani;
    private javax.swing.JTextField txtTanggalBuka;
    private javax.swing.JTextField txtTanggalHabis;
    private javax.swing.JTextField txtWaktuHabis;
    // End of variables declaration//GEN-END:variables
}
