/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import pbo2_2110010455.pbo2_2110010455;
import database.koneksi;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frameUtama extends javax.swing.JFrame {
    
    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDPetani = new javax.swing.JButton();
        btnDProvinsi = new javax.swing.JButton();
        btnDPembeli = new javax.swing.JButton();
        btnDBukaLelang = new javax.swing.JButton();
        btnDKomoditas = new javax.swing.JButton();
        btnDKabupaten = new javax.swing.JButton();
        btnDProsesLelang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("APLIKASI LELANG KOMODITAS PERTANIAN");

        btnDPetani.setText("Data Petani");
        btnDPetani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPetaniActionPerformed(evt);
            }
        });

        btnDProvinsi.setText("Data Provinsi");
        btnDProvinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDProvinsiActionPerformed(evt);
            }
        });

        btnDPembeli.setText("Data Pembeli");
        btnDPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPembeliActionPerformed(evt);
            }
        });

        btnDBukaLelang.setText("Data Buka Lelang");
        btnDBukaLelang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBukaLelangActionPerformed(evt);
            }
        });

        btnDKomoditas.setText("Data Komoditas");
        btnDKomoditas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKomoditasActionPerformed(evt);
            }
        });

        btnDKabupaten.setText("Data Kabupaten");
        btnDKabupaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKabupatenActionPerformed(evt);
            }
        });

        btnDProsesLelang.setText("Data Proses Lelang");
        btnDProsesLelang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDProsesLelangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDPetani)
                            .addComponent(btnDKomoditas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDProvinsi)
                                .addComponent(btnDKabupaten, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnDPembeli)
                            .addComponent(btnDBukaLelang)
                            .addComponent(btnDProsesLelang)))
                    .addComponent(jLabel1))
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDBukaLelang, btnDKabupaten, btnDKomoditas, btnDPembeli, btnDPetani, btnDProsesLelang, btnDProvinsi});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDPembeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDBukaLelang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDProsesLelang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDPetani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDKomoditas)))
                .addGap(38, 38, 38)
                .addComponent(btnDKabupaten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDProvinsi)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDKomoditasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKomoditasActionPerformed
        // TODO add your handling code here:
        new frameKomoditas().setVisible(true);
    }//GEN-LAST:event_btnDKomoditasActionPerformed

    private void btnDProvinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDProvinsiActionPerformed
        // TODO add your handling code here:
        new frameProvinsi().setVisible(true);
    }//GEN-LAST:event_btnDProvinsiActionPerformed

    private void btnDKabupatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKabupatenActionPerformed
        // TODO add your handling code here:
        new frameKabupaten().setVisible(true);
    }//GEN-LAST:event_btnDKabupatenActionPerformed

    private void btnDPetaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPetaniActionPerformed
        // TODO add your handling code here:
        new framePetani().setVisible(true);
    }//GEN-LAST:event_btnDPetaniActionPerformed

    private void btnDPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPembeliActionPerformed
        // TODO add your handling code here:
        new framePembeli().setVisible(true);
    }//GEN-LAST:event_btnDPembeliActionPerformed

    private void btnDBukaLelangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBukaLelangActionPerformed
        // TODO add your handling code here:
        new frameBukaLelang().setVisible(true);
    }//GEN-LAST:event_btnDBukaLelangActionPerformed

    private void btnDProsesLelangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDProsesLelangActionPerformed
        // TODO add your handling code here:
        new frameProsesLelang().setVisible(true);
    }//GEN-LAST:event_btnDProsesLelangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDBukaLelang;
    private javax.swing.JButton btnDKabupaten;
    private javax.swing.JButton btnDKomoditas;
    private javax.swing.JButton btnDPembeli;
    private javax.swing.JButton btnDPetani;
    private javax.swing.JButton btnDProsesLelang;
    private javax.swing.JButton btnDProvinsi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
