/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class framePetani extends javax.swing.JFrame {

    koneksi myObject;
    
    public DefaultTableModel modelTabelPetani;
    
    /**
     * Creates new form framePetani
     */
    public framePetani() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        myObject = new koneksi();
        modelTabelPetani = new DefaultTableModel();
        tabelPetani.setModel(modelTabelPetani);
        modelTabelPetani.addColumn("ID Petani");
        modelTabelPetani.addColumn("NIK");
        modelTabelPetani.addColumn("Jenis Kelamin");
        modelTabelPetani.addColumn("Tempat Lahir");
        modelTabelPetani.addColumn("Tanggal Lahir");
        modelTabelPetani.addColumn("Agama");
        modelTabelPetani.addColumn("Pernikahan");
        modelTabelPetani.addColumn("NPWP");
        modelTabelPetani.addColumn("Alamat");
        modelTabelPetani.addColumn("Kode Pos");
        modelTabelPetani.addColumn("ID Kabupaten");
        modelTabelPetani.addColumn("Nomor HP");
        modelTabelPetani.addColumn("Email");
        modelTabelPetani.addColumn("Tanggal Registrasi");
        tampilDataPetani();
    }
    
    public void tampilDataPetani() {
        try {
            modelTabelPetani.getDataVector().removeAllElements();
            modelTabelPetani.fireTableDataChanged();
            
            PreparedStatement query = myObject.konek.prepareStatement("SELECT * FROM petani");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[14];
                baris[0] = data.getString("id_petani");
                baris[1] = data.getString("nik");
                baris[2] = data.getString("jenis_kelamin");
                baris[3] = data.getString("tempat_lahir");
                baris[4] = data.getString("tanggal_lahir");
                baris[5] = data.getString("agama");
                baris[6] = data.getString("pernikahan");
                baris[7] = data.getString("npwp");
                baris[8] = data.getString("alamat");
                baris[9] = data.getString("kode_pos");
                baris[10] = data.getString("id_kabupaten");
                baris[11] = data.getString("nomor_hp");
                baris[12] = data.getString("email");
                baris[13] = data.getString("tanggal_registrasi");
                modelTabelPetani.addRow(baris);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDPetani = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJenisKelamin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTanggalLahir = new javax.swing.JTextField();
        txtAgama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPernikahan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNPWP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtKodePos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIDKabupaten = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTanggalRegistrasi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPetani = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tambah Data Petani");

        jLabel2.setText("ID Petani");

        jLabel3.setText("NIK");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Tempat Lahir");

        jLabel6.setText("Tanggal Lahir");

        jLabel7.setText("Agama");

        jLabel8.setText("Pernikahan");

        jLabel9.setText("NPWP");

        jLabel10.setText("Alamat");

        jLabel11.setText("Kode Pos");

        jLabel12.setText("ID Kabupaten");

        jLabel13.setText("No. Hp");

        jLabel14.setText("Email");

        jLabel15.setText("Tanggal Registrasi");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan PreparedStatement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelPetani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPetani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPetaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPetani);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel17.setText("Cari Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(79, 79, 79)
                                .addComponent(txtCari))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPernikahan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKodePos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIDKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIDPetani, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTanggalRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel1))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAgama, txtAlamat, txtEmail, txtIDKabupaten, txtIDPetani, txtJenisKelamin, txtKodePos, txtNPWP, txtNik, txtNoHp, txtPernikahan, txtTanggalLahir, txtTanggalRegistrasi, txtTempatLahir});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPernikahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggalRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (txtIDPetani.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Petani belum di isi!");
                txtIDPetani.requestFocus();
            } else if (txtNik.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "NIK belum di isi!");
                txtNik.requestFocus();
            } else if (txtJenisKelamin.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Jenis kelamin belum di isi!");
                txtJenisKelamin.requestFocus();
            } else if (txtTempatLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tempat lahir belum di isi!");
                txtTempatLahir.requestFocus();
            } else if (txtTanggalLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal lahir belum di isi!");
                txtTanggalLahir.requestFocus();
            } else if (txtAgama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Agama belum di isi!");
                txtAgama.requestFocus();
            } else if (txtPernikahan.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Pernikahan belum di isi!");
                txtPernikahan.requestFocus();
            } else if (txtNPWP.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "NPWP belum di isi!");
                txtNPWP.requestFocus();
            } else if (txtAlamat.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Alamat belum di isi!");
                txtAlamat.requestFocus();
            } else if (txtKodePos.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "KodePos belum di isi!");
                txtKodePos.requestFocus();
            } else if (txtIDKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Kabupaten belum di isi!");
                txtIDKabupaten.requestFocus();
            } else if (txtNoHp.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No.Hp belum di isi!");
                txtNoHp.requestFocus();
            } else if (txtEmail.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Email belum di isi!");
                txtEmail.requestFocus();
            } else if (txtTanggalRegistrasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal Registrasi belum di isi!");
                txtTanggalRegistrasi.requestFocus();
            } else {
                String sql = "insert into petani value ('"+txtIDPetani.getText()+"','"+txtNik.getText()+"','"+txtJenisKelamin.getText()+"','"+txtTempatLahir.getText()+"','"+txtTanggalLahir.getText()+"','"+txtAgama.getText()+"','"+txtPernikahan.getText()+"','"+txtNPWP.getText()+"','"+txtAlamat.getText()+"','"+txtKodePos.getText()+"','"+txtIDKabupaten.getText()+"','"+txtNoHp.getText()+"','"+txtEmail.getText()+"','"+txtTanggalRegistrasi.getText()+"')";
                myObject.konek.createStatement().execute(sql);
                tampilDataPetani();
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDPetani.getText().isEmpty()) &&
                    (txtNik.getText().isEmpty()) &&
                    (txtJenisKelamin.getText().isEmpty()) &&
                    (txtTempatLahir.getText().isEmpty()) &&
                    (txtTanggalLahir.getText().isEmpty()) &&
                    (txtAgama.getText().isEmpty()) &&
                    (txtPernikahan.getText().isEmpty()) &&
                    (txtNPWP.getText().isEmpty()) &&
                    (txtAlamat.getText().isEmpty()) &&
                    (txtKodePos.getText().isEmpty()) &&
                    (txtIDKabupaten.getText().isEmpty()) &&
                    (txtNoHp.getText().isEmpty()) &&
                    (txtEmail.getText().isEmpty()) &&
                    (txtTanggalRegistrasi.getText().isEmpty()) 
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE petani SET nik=?, jenis_kelamin=?, tempat_lahir=?, tanggal_lahir=?, agama=?, pernikahan=?, npwp=?, alamat=?, kode_pos=?, id_kabupaten=?, nomor_hp=?, email=?, tanggal_registrasi=? WHERE id_petani=?";
                PreparedStatement ubah = myObject.konek.prepareStatement(sql);
                ubah.setString(1, txtNik.getText());
                ubah.setString(2, txtJenisKelamin.getText());
                ubah.setString(3, txtTempatLahir.getText());
                ubah.setString(4, txtTanggalLahir.getText());
                ubah.setString(5, txtAgama.getText());
                ubah.setString(6, txtPernikahan.getText());
                ubah.setString(7, txtNPWP.getText());
                ubah.setString(8, txtAlamat.getText());
                ubah.setString(9, txtKodePos.getText());
                ubah.setString(10, txtIDKabupaten.getText());
                ubah.setString(11, txtNoHp.getText());
                ubah.setString(12, txtEmail.getText());
                ubah.setString(13, txtTanggalRegistrasi.getText());
                ubah.setString(14, txtIDPetani.getText());
                ubah.executeUpdate();
                tampilDataPetani();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDPetani.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Petani belum di isi!");
                txtIDPetani.requestFocus();
            } else if (txtNik.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "NIK belum di isi!");
                txtNik.requestFocus();
            } else if (txtJenisKelamin.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Jenis kelamin belum di isi!");
                txtJenisKelamin.requestFocus();
            } else if (txtTempatLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tempat lahir belum di isi!");
                txtTempatLahir.requestFocus();
            } else if (txtTanggalLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal lahir belum di isi!");
                txtTanggalLahir.requestFocus();
            } else if (txtAgama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Agama belum di isi!");
                txtAgama.requestFocus();
            } else if (txtPernikahan.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Pernikahan belum di isi!");
                txtPernikahan.requestFocus();
            } else if (txtNPWP.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "NPWP belum di isi!");
                txtNPWP.requestFocus();
            } else if (txtAlamat.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Alamat belum di isi!");
                txtAlamat.requestFocus();
            } else if (txtKodePos.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "KodePos belum di isi!");
                txtKodePos.requestFocus();
            } else if (txtIDKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Kabupaten belum di isi!");
                txtIDKabupaten.requestFocus();
            } else if (txtNoHp.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No.Hp belum di isi!");
                txtNoHp.requestFocus();
            } else if (txtEmail.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Email belum di isi!");
                txtEmail.requestFocus();
            } else if (txtTanggalRegistrasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal Registrasi belum di isi!");
                txtTanggalRegistrasi.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM petani WHERE id_petani ='"+txtIDPetani.getText()+"'";
                ResultSet cari = myObject.konek.createStatement().executeQuery(sqlCari);
                if(cari.next()){
                    JOptionPane.showMessageDialog(this, "ID Petani sudah terdaftar!!!");
                                         
                    txtNik.setText(cari.getString(2));
                    txtJenisKelamin.setText(cari.getString(3));
                    txtTempatLahir.setText(cari.getString(4));
                    txtTanggalLahir.setText(cari.getString(5));
                    txtAgama.setText(cari.getString(6));
                    txtPernikahan.setText(cari.getString(7));
                    txtNPWP.setText(cari.getString(8));
                    txtAlamat.setText(cari.getString(9));
                    txtKodePos.setText(cari.getString(10));
                    txtIDKabupaten.setText(cari.getString(11));
                    txtNoHp.setText(cari.getString(12));
                    txtEmail.setText(cari.getString(13));
                    txtTanggalRegistrasi.setText(cari.getString(14));
                    
                } else {
                    String sql = "INSERT INTO petani VALUE (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement simpan = myObject.konek.prepareStatement(sql);
                    simpan.setString(1, txtIDPetani.getText());
                    simpan.setString(2, txtNik.getText());
                    simpan.setString(3, txtJenisKelamin.getText());
                    simpan.setString(4, txtTempatLahir.getText());
                    simpan.setString(5, txtTanggalLahir.getText());
                    simpan.setString(6, txtAgama.getText());
                    simpan.setString(7, txtPernikahan.getText());
                    simpan.setString(8, txtNPWP.getText());
                    simpan.setString(9, txtAlamat.getText());
                    simpan.setString(10, txtKodePos.getText());
                    simpan.setString(11, txtIDKabupaten.getText());
                    simpan.setString(12, txtNoHp.getText());
                    simpan.setString(13, txtEmail.getText());
                    simpan.setString(14, txtTanggalRegistrasi.getText());
                    simpan.executeUpdate();
                    tampilDataPetani();
                    JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelPetaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPetaniMouseClicked
        // TODO add your handling code here:
        int baris = tabelPetani.getSelectedRow();
        String id_petani = tabelPetani.getValueAt(baris, 0).toString();
        String nik = tabelPetani.getValueAt(baris, 1).toString();
        String jenis_kelamin = tabelPetani.getValueAt(baris, 2).toString();
        String tempat_lahir = tabelPetani.getValueAt(baris, 3).toString();
        String tanggal_lahir = tabelPetani.getValueAt(baris, 4).toString();
        String agama = tabelPetani.getValueAt(baris, 5).toString();
        String pernikahan = tabelPetani.getValueAt(baris, 6).toString();
        String npwp = tabelPetani.getValueAt(baris, 7).toString();
        String alamat = tabelPetani.getValueAt(baris, 8).toString();
        String kode_pos = tabelPetani.getValueAt(baris, 9).toString();
        String id_kabupaten = tabelPetani.getValueAt(baris, 10).toString();
        String nomor_hp = tabelPetani.getValueAt(baris, 11).toString();
        String email = tabelPetani.getValueAt(baris, 12).toString();
        String tanggal_registrasi = tabelPetani.getValueAt(baris, 13).toString();
        txtIDPetani.setText(id_petani);
        txtNik.setText(nik);
        txtJenisKelamin.setText(jenis_kelamin);
        txtTempatLahir.setText(tempat_lahir);
        txtTanggalLahir.setText(tanggal_lahir);
        txtAgama.setText(agama);
        txtPernikahan.setText(pernikahan);
        txtNPWP.setText(npwp);
        txtAlamat.setText(alamat);
        txtKodePos.setText(kode_pos);
        txtIDKabupaten.setText(id_kabupaten);
        txtNoHp.setText(nomor_hp);
        txtEmail.setText(email);
        txtTanggalRegistrasi.setText(tanggal_registrasi);
    }//GEN-LAST:event_tabelPetaniMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDPetani.getText().isEmpty()) &&
                    (txtNik.getText().isEmpty()) &&
                    (txtJenisKelamin.getText().isEmpty()) &&
                    (txtTempatLahir.getText().isEmpty()) &&
                    (txtTanggalLahir.getText().isEmpty()) &&
                    (txtAgama.getText().isEmpty()) &&
                    (txtPernikahan.getText().isEmpty()) &&
                    (txtNPWP.getText().isEmpty()) &&
                    (txtAlamat.getText().isEmpty()) &&
                    (txtKodePos.getText().isEmpty()) &&
                    (txtIDKabupaten.getText().isEmpty()) &&
                    (txtNoHp.getText().isEmpty()) &&
                    (txtEmail.getText().isEmpty()) &&
                    (txtTanggalRegistrasi.getText().isEmpty()) 
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM petani WHERE id_petani=?";
                PreparedStatement hapus = myObject.konek.prepareStatement(sql);
                hapus.setString(1, txtIDPetani.getText());
                hapus.executeUpdate();
                tampilDataPetani();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        modelTabelPetani.getDataVector().removeAllElements();
        modelTabelPetani.fireTableDataChanged();
        try {
            String sqlcari = "SELECT * FROM petani WHERE id_petani LIKE '%"+txtCari.getText()+"%' "
                        + "OR nik LIKE '%"+txtCari.getText()+"%' OR jenis_kelamin LIKE '%"+txtCari.getText()+"%'"
                        + "OR tempat_lahir LIKE '%"+txtCari.getText()+"%' OR tanggal_lahir LIKE '%"+txtCari.getText()+"%'"
                        + "OR agama LIKE '%"+txtCari.getText()+"%' OR pernikahan LIKE '%"+txtCari.getText()+"%'"
                        + "OR npwp LIKE '%"+txtCari.getText()+"%' OR alamat LIKE '%"+txtCari.getText()+"%'"
                        + "OR kode_pos LIKE '%"+txtCari.getText()+"%' OR id_kabupaten LIKE '%"+txtCari.getText()+"%'"
                        + "OR nomor_hp LIKE '%"+txtCari.getText()+"%' OR email LIKE '%"+txtCari.getText()+"%'"
                        + "OR tanggal_registrasi LIKE '%"+txtCari.getText()+"%'";
            Statement cari = myObject.konek.createStatement();
            ResultSet data = cari.executeQuery(sqlcari);
            while (data.next()) {                
                Object[] baris = new Object[14];
                baris[0] = data.getString("id_petani");
                baris[1] = data.getString("nik");
                baris[2] = data.getString("jenis_kelamin");
                baris[3] = data.getString("tempat_lahir");
                baris[4] = data.getString("tanggal_lahir");
                baris[5] = data.getString("agama");
                baris[6] = data.getString("pernikahan");
                baris[7] = data.getString("npwp");
                baris[8] = data.getString("alamat");
                baris[9] = data.getString("kode_pos");
                baris[10] = data.getString("id_kabupaten");
                baris[11] = data.getString("nomor_hp");
                baris[12] = data.getString("email");
                baris[13] = data.getString("tanggal_registrasi");
                modelTabelPetani.addRow(baris);   
            }
            cari.close();
            data.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePetani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPetani;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDKabupaten;
    private javax.swing.JTextField txtIDPetani;
    private javax.swing.JTextField txtJenisKelamin;
    private javax.swing.JTextField txtKodePos;
    private javax.swing.JTextField txtNPWP;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtPernikahan;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtTanggalRegistrasi;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
