/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class frameKabupaten extends javax.swing.JFrame {

    koneksi myObject;

    public DefaultTableModel modelTabelKabupaten;
    
    /**
     * Creates new form frameKabupaten
     */
    public frameKabupaten() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        myObject = new koneksi();
        modelTabelKabupaten = new DefaultTableModel();
        tabelKabupaten.setModel(modelTabelKabupaten);
        modelTabelKabupaten.addColumn("ID Kabupaten");
        modelTabelKabupaten.addColumn("Nama Kabupaten");
        modelTabelKabupaten.addColumn("ID Provinsi");
        tampilDataKabupaten();
        
    }
        
    public void tampilDataKabupaten() {
        try {
            modelTabelKabupaten.getDataVector().removeAllElements();
            modelTabelKabupaten.fireTableDataChanged();
            
            PreparedStatement query = myObject.konek.prepareStatement("SELECT * FROM kabupaten");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[3];
                baris[0] = data.getString("id_kabupaten");
                baris[1] = data.getString("nama_kabupaten");
                baris[2] = data.getString("id_provinsi");
                modelTabelKabupaten.addRow(baris);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtNamaKabupaten = new javax.swing.JTextField();
        txtIDProvinsi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDKabupaten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKabupaten = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("ID Provinsi");

        jLabel4.setText("ID Kabupaten");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tambah Data Kabupaten");

        jLabel2.setText("Nama Kabupaten");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan PreparedStatement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelKabupaten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKabupaten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKabupatenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKabupaten);

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel10.setText("Cari Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNamaKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIDProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIDKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIDKabupaten, txtIDProvinsi, txtNamaKabupaten});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (txtIDKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID kabupaten belum di isi!");
                txtIDKabupaten.requestFocus();
            } else if (txtNamaKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama kabupaten belum di isi!");
                txtNamaKabupaten.requestFocus();
            } else if (txtIDProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Provinsi belum di isi!");
                txtIDProvinsi.requestFocus();
            } else {
                String sql = "insert into kabupaten value ('"+txtIDKabupaten.getText()+"','"+txtNamaKabupaten.getText()+"','"+txtIDProvinsi.getText()+"')";
                myObject.konek.createStatement().execute(sql);
                tampilDataKabupaten();
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIDKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID kabupaten belum di isi!");
                txtIDKabupaten.requestFocus();
            } else if (txtNamaKabupaten.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama kabupaten belum di isi!");
                txtNamaKabupaten.requestFocus();
            } else if (txtIDProvinsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID Provinsi belum di isi!");
                txtIDProvinsi.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM kabupaten WHERE id_kabupaten ='"+txtIDKabupaten.getText()+"'";
                ResultSet cari = myObject.konek.createStatement().executeQuery(sqlCari);
                if(cari.next()){
                    JOptionPane.showMessageDialog(this, "ID Kabupaten sudah terdaftar!!!");
                                         
                    txtNamaKabupaten.setText(cari.getString(2));
                    txtIDProvinsi.setText(cari.getString(3));
                    
                } else {
                    String sql = "INSERT INTO kabupaten VALUE (?, ?, ?)";
                    PreparedStatement simpan = myObject.konek.prepareStatement(sql);
                    simpan.setString(1, txtIDKabupaten.getText());
                    simpan.setString(2, txtNamaKabupaten.getText());
                    simpan.setString(3, txtIDProvinsi.getText());
                    simpan.executeUpdate();
                    tampilDataKabupaten();
                    JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelKabupatenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKabupatenMouseClicked
        // TODO add your handling code here:
        int baris = tabelKabupaten.getSelectedRow();
        String id_kabupaten = tabelKabupaten.getValueAt(baris, 0).toString();
        String nama_kabupaten = tabelKabupaten.getValueAt(baris, 1).toString();
        String id_provinsi = tabelKabupaten.getValueAt(baris, 2).toString();
        txtIDKabupaten.setText(id_kabupaten);
        txtNamaKabupaten.setText(nama_kabupaten);
        txtIDProvinsi.setText(id_provinsi);
    }//GEN-LAST:event_tabelKabupatenMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDKabupaten.getText().isEmpty()) &&
                    (txtNamaKabupaten.getText().isEmpty()) &&
                    (txtIDProvinsi.getText().isEmpty()) 
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE kabupaten SET nama_kabupaten=?, id_provinsi=? WHERE id_kabupaten=?";
                PreparedStatement ubah = myObject.konek.prepareStatement(sql);
                ubah.setString(1, txtNamaKabupaten.getText());
                ubah.setString(2, txtIDProvinsi.getText());
                ubah.setString(3, txtIDKabupaten.getText());
                ubah.executeUpdate();
                tampilDataKabupaten();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtIDKabupaten.getText().isEmpty()) &&
                    (txtNamaKabupaten.getText().isEmpty()) &&
                    (txtIDProvinsi.getText().isEmpty()) 
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM kabupaten WHERE id_kabupaten=?";
                PreparedStatement hapus = myObject.konek.prepareStatement(sql);
                hapus.setString(1, txtIDKabupaten.getText());
                hapus.executeUpdate();
                tampilDataKabupaten();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        modelTabelKabupaten.getDataVector().removeAllElements();
        modelTabelKabupaten.fireTableDataChanged();
        try {
            String sqlcari = "SELECT * FROM kabupaten WHERE id_kabupaten LIKE '%"+txtCari.getText()+"%' "
                        + "OR nama_kabupaten LIKE '%"+txtCari.getText()+"%' OR id_provinsi LIKE '%"+txtCari.getText()+"%'";
            Statement cari = myObject.konek.createStatement();
            ResultSet data = cari.executeQuery(sqlcari);
            while (data.next()) {                
                Object[] baris = new Object[3];
                baris[0] = data.getString("id_kabupaten");
                baris[1] = data.getString("nama_kabupaten");
                baris[2] = data.getString("id_provinsi");
                modelTabelKabupaten.addRow(baris);   
            }
            cari.close();
            data.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameKabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameKabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameKabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameKabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameKabupaten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKabupaten;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIDKabupaten;
    private javax.swing.JTextField txtIDProvinsi;
    private javax.swing.JTextField txtNamaKabupaten;
    // End of variables declaration//GEN-END:variables
}
